name: Continuous Build and Test
on:
  push:
    branches:
      - main
jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9      
      - name: Install pytest
        run: python -m pip install pytest
      - name: Run Unit Tests
        run: python -m unittest discover
      - name: Run Integration Tests
        run: pytest -v  
